### ISSUE TITLE
Do not truncate ytccf.sh table output when thumbnails are disabled

### ISSUE THREAD

**Issue by wavexx** [woefe/ytcc#105]
**Is your feature request related to a problem? Please describe.**
The table output in ytccf.sh is truncated due to thumbnail supports.
This makes the title column essentially useless on ~90 columns already.

**Describe the solution you'd like**
If thumbnails are not available or disabled, the table should be kept at full width.

**Comment by woefe** [comment]
Fixed in d1e56a1

**Comment by wavexx** [comment]
I noticed that truncation still happes if you perform an update with Alt-R: starts with full width, but gets truncated immediately after the update

**Comment by woefe** [comment]
Not sure why this happens. I think it's unrelated to the recent fix. What version of fzf are you using? I think something changed in fzf (or a dependency of fzf). Passing the width calculation to the fzf bindings stopped working for some reason. I've fixed it in 0e27951.

**Comment by wavexx** [comment]
fzf 0.24 (devel) from debian unstable.

I can't say when/if this started due to fzf though, I didn't notice the truncation right away.

**Comment by woefe** [comment]
I'm not sure what changed. I ran a git bisect with an older version of fzf and it seems it hasn't been working since quite a while. 8fcf4e1 introduced the bug. I'm pretty sure that it was working until just a bit over a week ago.

I'm not completely happy with the fix in 0e27951, because it does not recalculate the width after `<alt+r>` in case the terminal width changed. I'm pretty sure that was working at some point and I liked that.

ff82abe fixes the behavior:
- Resizing after `<alt+r>` if terminal width changed
- No resizing after `<alt+r>` unless terminal width changed
- Full width with `--no-thumbnails`
