### ISSUE TITLE
Duration Column

### ISSUE THREAD

**Issue by zoidby** [woefe/ytcc#25]
I often only have time to watch a short video, but you only see the duration after starting one. Thus i often have to cancel videos until i find a short one.

Would it be possible to add a duration column, so one could see the time needed right away?

**Comment by woefe** [comment]
I like the idea, but with the current code base it is not so easy to implement and will slow the updating process down significantly, because the feeds do not provide this info. Instead, it would be implemented through youtube-dl, which can provide more metadata about a video. Letting youtube-dl fetch new metadata on every update probably slows things down significantly.

I'll think more about it for a v2 of ytcc.

**Comment by woefe** [comment]
The duration column is now available in the v2 branch. v2 is still very unstable. I'll update the README as soon as I have a beta version ready.

I was able to get fast updating with youtube-dl working by making use of youtube-dl internals. The duration column is still not very readably see #32 .
