### ISSUE TITLE
Feature: Option to use custom playlist name in youtube_dl output

### ISSUE THREAD

**Issue by just-for-reporting-issues** [woefe/ytcc#82]
**Is your feature request related to a problem? Please describe.**

Unable to use the same custom 'name' (ytcc rename) defined in ytcc as youtube_dl output. 

**Describe the solution you'd like**

Would be great to allow the name we define in ytcc to be used as an output in the youtube_dl format option. For example instead of using something like this: 

```
[youtube_dl]
output_template = %(uploader)s/%(title)s.%(ext)s
```

We can use this: 

```
[youtube_dl]
output_template = %(ytcc_name)s/%(title)s.%(ext)s
```

**Additional context**

Would be nice to have a youtube_dl flags options the same as mpv does. Some youtubers have crazy titles (emojii's etc) so being able to pass in `--restrict-filenames` would be nice.

**Comment by woefe** [comment]
Adding a restrict_filenames option to the config shouldn't be a problem.

But using the ytcc name in the `output_template` is tricky, because `youtube_dl` is not aware of that name. I could probably override the name after youtube_dl's info extraction and the actual download. But using the ytcc name has another problem: the name is not unique, because a video can be on multiple playlists. Which name should we use in case there is more than one? This will  lead to unexpected behavior in the future.

**Comment by woefe** [comment]
`restrict_filenames` introduced in 916f112
