### ISSUE TITLE
Feature: Skip videos over certain duration

### ISSUE THREAD

**Issue by just-for-reporting-issues** [woefe/ytcc#83]
**Is your feature request related to a problem? Please describe.**

While we can skip livestreaming while live (fantastic) some youtubers now convert livestreams to videos after broadcast, these can last hours and be quite a sizable download (3G+). 

**Describe the solution you'd like**

It looks like ytcc knows the duration of the video before downloading. Having an option to skip/mark videos longer than X duration in minutes would solve this.

```
[ytcc] 
max_duration=120
```

**Comment by woefe** [comment]
Fixed in 09b7b3d.

I was first trying to implement the `max_filesize` option that youtube_dl provides, but ran into issues because it's not straightforward to control the youtube_dl downloader (setup proper logging or check the download/skipped result). So, instead there is a `max_duration` option in the `youtube_dl` section of the config file now (very similar to what @just-for-reporting-issues proposed).
